resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:
- name: project-prs
  type: pull-request
  source:
    repo: DaftTrick/concource-pr-test
    access_token: {{github_access_token}}
    private_key: {{github_private_key}}

jobs:
  - name: test-pr-vmware
    plan:
      - get: project-prs
        trigger: true
        version: every
      - put: project-prs
        params:
          path: project-prs
          status: success
          context: role2
      - task: rspec
        privileged: true
        config:
          image_resource:
            type: docker-image
            source:
              repository: jtarchie/pr
              tag: test
          inputs:
            - name: project-prs
          platform: linux
          run:
            path: sh
            args: ['-c', 'cd project-prs && bundle install && bundle exec rspec']
        on_success:
          put: project-prs
          params:
            path: project-prs
            status: success
            context: role1
        on_failure:
          put: project-prs
          params:
            path: project-prs
            status: failure
            context: role1
